name: Docker Build and Deploy

on:
  push:
    branches: [ main ]  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Copy repository to home server and build Docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/aguilarcarboni/Documents/Coding/laserfocus-api
          git pull origin main
          docker build -t laserfocus-api:latest .
          docker-compose up -d